### ISSUE TITLE
Problem with NEC UPD720202

### ISSUE THREAD

**Issue by Predatux** [chris1111/USB-3.0-NEC#1]
Hey, thanks for the help.
I have a NEC UPD72020202 PCIExpress card. I installed the kext, and now I get a switch to turn off the device, but when I connect any flash drive to the adapter it is not recognized by the system.
The device does not appear mounted on the desktop, nor does the disk utility recognize it.
What works is the charge. If I connect a small camera, it charges, but I can't access it.
On the other hand, if I plug in a flash drive, and I suddenly disconnect it, I get the notification that I have incorrectly removed the device.
I use High Sierra 10.13.6

Thank you

**Comment by chris1111** [comment]
NEC/Renesas: D720200
I think this is not the right kext for you ?
Remove the kext and you can try this
Source ➤ AppleUSBXHCI v710.4.11 (10.10.5)](https://www.insanelymac.com/forum/files/file/150-patched-appleusbxhci/)

Use  AppleUSBXHCI v710.4.11 (10.10.5)
