### ISSUE TITLE
Issue with USB3.0 hub (monitor)

### ISSUE THREAD

**Issue by asheenlevrai** [chris1111/USB-3.0-NEC#3]
Hi :)

I was wondering if there are any steps I should take BEFORE installing _USB 3.0 NEC.pkg_ onto my Mojave (10.14.3) rig sporting the following USB3.0 chip:
 - Etron EJ168

Should I remove _GenericUSBXHCI.kext_?
Should I remove _USBinjectAll.kext_?

Should I make any other changes?

Thanks a lot for your help.
Best,
-a-

EDIT:
I tried my luck and did the following:
- Deleted _GenericUSBXHCI.kext_
- installed _mXHCD.kext_ (via _USB3.0 NEC.pkg_)
- rebooted

Now:
- No more error message at boot whatsoever
( - all USB2.0 ports behave as expected)
- both USB3.0 ports on the back of the tower work at full speed (yes!)

**However**
If I connect the monitor (= USB3.0 hub) on one of the USB3.0 ports:
- The remaining USB3.0 port on the tower still works normally
- none (0/3) of the USB3.0 ports on the monitor work (as if disabled)

Maybe this can be fixed?
Should _mXHCD.kext_ be patched or updated?

note: I get the same results if I keep or delete _USBInjectAll.kext_ as well

Thank you for your help.

Best,
-a-

**Comment by chris1111** [comment]
> mXHCD.kext

You tried and did the good things
:mXHCD.kext will not be update anymore!
